┌─╴Ansi
  # Regular text
  Black   ← "\x1b[0;30m"
  Red     ← "\x1b[0;31m"
  Green   ← "\x1b[0;32m"
  Yellow  ← "\x1b[0;33m"
  Blue    ← "\x1b[0;34m"
  Magenta ← "\x1b[0;35m"
  Cyan    ← "\x1b[0;36m"
  White   ← "\x1b[0;37m"

  # Regular bold text
  BoldBlack   ← "\x1b[1;30m"
  BoldRed     ← "\x1b[1;31m"
  BoldGreen   ← "\x1b[1;32m"
  BoldYellow  ← "\x1b[1;33m"
  BoldBlue    ← "\x1b[1;34m"
  BoldMagenta ← "\x1b[1;35m"
  BoldCyan    ← "\x1b[1;36m"
  BoldWhite   ← "\x1b[0m\x1b[1;37m"
  BoldUWhite  ← "\x1b[1;4;37m"

  # Regular underline text
  UnderlineBlack   ← "\x1b[4;30m"
  UnderlineRed     ← "\x1b[4;31m"
  UnderlineGreen   ← "\x1b[4;32m"
  UnderlineYellow  ← "\x1b[4;33m"
  UnderlineBlue    ← "\x1b[4;34m"
  UnderlineMagenta ← "\x1b[4;35m"
  UnderlineCyan    ← "\x1b[4;36m"
  UnderlineWhite   ← "\x1b[4;37m"

  # Regular background
  BackgroundBlack   ← "\x1b[40m"
  BackgroundRed     ← "\x1b[41m"
  BackgroundGreen   ← "\x1b[42m"
  BackgroundYellow  ← "\x1b[43m"
  BackgroundBlue    ← "\x1b[44m"
  BackgroundMagenta ← "\x1b[45m"
  BackgroundCyan    ← "\x1b[46m"
  BackgroundWhite   ← "\x1b[47m"
  BlackOnWhite      ← "\x1b[30;47m"

  # High intensity background
  HighBackgroundBlack   ← "\x1b[0;100m"
  HighBackgroundRed     ← "\x1b[0;101m"
  HighBackgroundGreen   ← "\x1b[0;102m"
  HighBackgroundYellow  ← "\x1b[0;103m"
  HighBackgroundBlue    ← "\x1b[0;104m"
  HighBackgroundMagenta ← "\x1b[0;105m"
  HighBackgroundCyan    ← "\x1b[0;106m"
  HighBackgroundWhite   ← "\x1b[0;107m"

  # High intensity text
  HighBlack   ← "\x1b[0;90m"
  HighRed     ← "\x1b[0;91m"
  HighGreen   ← "\x1b[0;92m"
  HighYellow  ← "\x1b[0;93m"
  HighBlue    ← "\x1b[0;94m"
  HighMagenta ← "\x1b[0;95m"
  HighCyan    ← "\x1b[0;96m"
  HighWhite   ← "\x1b[0;97m"

  # Bold high intensity text
  BoldHighBlack   ← "\x1b[1;90m"
  BoldHighRed     ← "\x1b[1;91m"
  BoldHighGreen   ← "\x1b[1;92m"
  BoldHighYellow  ← "\x1b[1;93m"
  BoldHighBlue    ← "\x1b[1;94m"
  BoldHighMagenta ← "\x1b[1;95m"
  BoldHighCyan    ← "\x1b[1;96m"
  BoldHighWhite   ← "\x1b[1;97m"

  # Reset codes
  Reset      ← "\x1b[m"
  CReset     ← "\x1b[0m"
  ColorReset ← "\x1b[0m"

  # Special styles
  Invert      ← "\x1b[7m"
  ItalicGrey  ← "\x1b[3;90m"
  Italic      ← "\x1b[3m"
  ItalicWhite ← "\x1b[0m\x1b[3;37m"
  RedStruck   ← "\x1b[9m"
└─╴
